version: "3.8"

services:
  web:
    build: .
    container_name: dev_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: dev_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "15432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
